export const data = [
  {
    jobTitle: "Web/Social Media Associate",
    company: " Anonymous Employer",
    location: "Lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design ",
    itemValue: "tech",
    time: "16h",
    requirement: `We are looking to hire an innovative Social Media associate who will be responsible to drive our goals through multiple social media channels and unique profiles. You will work closely with the digital manager to increase brand awareness, drive prospects to brand websites, and 
                    engaging influencers via paid and organic social media presence. 
        `,
  },
  {
    jobTitle: "Accountant",
    company: "STRAACOS",
    location: "Lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000 Negotiable",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    time: "17h",
    requirement: ` 
             Are you a brilliant accountant with pristine accuracy at your Job with?
            Our Client is in search of bright and outstanding accountants who can go on a beautiful adventure of numbers and grow in career and as an individual as they value balance. 
    `,
  },
  {
    jobTitle: " Marketer",
    company: "IMPACT EMPOWERMENT CENTRE",
    location: "Lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: " Accounting, Auditing & Finance",
    itemValue: "accounting",
    time: "17h",
    requirement: ` We are looking for a suitable candidate to fill this position.`,
  },
  {
    jobTitle: "Executive Assistant",
    company: "Studenthubng",
    location: "Lagos",
    jobType: "Full Time ",
    salary: "Less than 75,000",
    jobModule: "Admin & Office",
    itemValue: "admin",
    time: "17h",
    requirement: `
                We are looking to employ an Executive Assistant for our client. You will manage mostly business-related tasks for the team such as creating reports, organizing travel and accommodation, taking minutes, and other organizational tasks. 
    `,
  },
  {
    jobTitle: " Purchase Specialist",
    company: "STRAACOS",
    location: "Lagos",
    jobType: "Full Time ",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Farming & Agriculture",
    itemValue: "farming",
    time: "17h",
    requirement: `
        My client is an agribusiness company that accelerates the process of farming, supply and ensure enduser access to produce using cutting-edge technlogy, advance farm mechanism and excellent partneships to deliver internal and external customer satisfaction. We are looking for a motivated Purchasing Specialist to ensure we deliver quality service. 
    `,
  },
  //   {
  //     jobTitle: "",
  //     company: "",
  //     location: "",
  //     jobType: "",
  //     salary: "",
  //     jobModule: "",
  //     time: "",
  //     requirement: ``,
  //   },
  //   {
  //     jobTitle: "",
  //     company: "",
  //     location: "",
  //     jobType: "",
  //     salary: "",
  //     jobModule: "",
  //     time: "",
  //     requirement: ``,
  //   },
  //   {
  //     jobTitle: "",
  //     company: "",
  //     location: "",
  //     jobType: "",
  //     salary: "",
  //     jobModule: "",
  //     time: "",
  //     requirement: ``,
  //   },
  //   {
  //     jobTitle: "",
  //     company: "",
  //     location: "",
  //     jobType: "",
  //     salary: "",
  //     jobModule: "",
  //     time: "",
  //     requirement: ``,
  //   },
  //   {
  //     jobTitle: "",
  //     company: "",
  //     location: "",
  //     jobType: "",
  //     salary: "",
  //     jobModule: "",
  //     time: "",
  //     requirement: ``,
  //   },
];
