export const data = [
  {
    jobTitle: "Web/Social Media Associate",
    company: " Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design ",
    itemValue: "creative",
    time: "16h",
    requirement: `We are looking to hire an innovative Social Media associate who will be responsible to drive our goals through multiple social media channels and unique profiles. You will work closely with the digital manager to increase brand awareness, drive prospects to brand websites, and 
                    engaging influencers via paid and organic social media presence. 
        `,
  },
  {
    jobTitle: "Accountant",
    company: "STRAACOS",
    location: "lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000 Negotiable",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    time: "17h",
    requirement: ` 
             Are you a brilliant accountant with pristine accuracy at your Job with?
            Our Client is in search of bright and outstanding accountants who can go on a beautiful adventure of numbers and grow in career and as an individual as they value balance. 
    `,
  },
  {
    jobTitle: " Marketer",
    company: "IMPACT EMPOWERMENT CENTRE",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: " Accounting, Auditing & Finance",
    itemValue: "accounting",
    time: "17h",
    requirement: ` We are looking for a suitable candidate to fill this position.`,
  },
  {
    jobTitle: "Executive Assistant",
    company: "Studenthubng",
    location: "lagos",
    jobType: "Full Time ",
    salary: "Less than 75,000",
    jobModule: "Admin & Office",
    itemValue: "admin",
    time: "17h",
    requirement: `
                We are looking to employ an Executive Assistant for our client. You will manage mostly business-related tasks for the team such as creating reports, organizing travel and accommodation, taking minutes, and other organizational tasks. 
    `,
  },
  {
    jobTitle: " Purchase Specialist",
    company: "STRAACOS",
    location: "lagos",
    jobType: "Full Time ",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Farming & Agriculture",
    itemValue: "farming",
    time: "17h",
    requirement: `
        My client is an agribusiness company that accelerates the process of farming, supply and ensure enduser access to produce using cutting-edge technlogy, advance farm mechanism and excellent partneships to deliver internal and external customer satisfaction. We are looking for a motivated Purchasing Specialist to ensure we deliver quality service. 
    `,
  },
  {
    jobTitle: "Project Manager (Fin-Tech)",
    company: "Deecla Services Ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: "250,000 - 400,000",
    jobModule: "Product & Project Management",
    itemValue: "projectManagement",
    time: "18h",
    requirement: `The candidate should be able to meet the business needs of the firm by planning and organizing resources 
    and people for the management of information technology projects from inception to completion.`,
  },
  {
    jobTitle: "Quality Assurance Engineers",
    company: "ARC",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Quality Control & Assurance",
    itemValue: "qualityControl",
    time: "18h",
    requirement: `You will be embedded in the Product Engineering team and work in multidisciplinary product squads, to carry out comprehensive quality assurance testing for our products. We welcome QA engineers from all technical backgrounds who are happy to bring their experiences on board. 
You will have to demonstrate excellent problem-solving skills.
`,
  },
  {
    jobTitle: "Business Solutions Representative",
    company: "RyteGate Construction & Technologies Ltd.",
    location: "imo",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    time: "18h",
    requirement: `Direct / In-Person Marketing of RyteGate Range of Products to generate Awareness and Sales.`,
  },
  {
    jobTitle: "Sales Executive",
    company: "Sigma Consulting Group",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    time: "18h",
    requirement: `Our Organization is currently recruiting for the services of a Sales Executive, who has industry knowledge of the Architectural and Construction space `,
  },
  {
    jobTitle: " 2d and 3d animator & motion graphics designer",
    company: "gentleman studio medis",
    location: "lagos",
    jobType: "Full Time ",
    salary: "75,000 - 150,000",
    jobModule: "Creative & Design",
    itemValue: "creative",
    time: "18h",
    requirement: `2D animator to help create websites, video games, advertisements, and videos.
`,
  },
  {
    jobTitle: "Porter ",
    company: "Cr8 Careers Limited",
    location: "rest of nigeria (delta)",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    time: "18h",
    requirement: `An up scale Hotel is looking to employ an experience personnel for its operation
Accountant`,
  },
  {
    jobTitle: "Accountant",
    company: "Cr8 Careers Limited",
    location: "rest of nigeria (delta)",
    jobType: "Full Time ",
    salary: "150,000 - 250,000 Negotiable",
    jobModule: "Hospitality & Leisure",
    itemValue: "accounting",
    time: "18h",
    requirement: `An up scale Hotel is looking to employ an experience personnel for its operation
Accountant`,
  },
  {
    jobTitle: "Laundry Attendant",
    company: "Cr8 Careers Limited",
    location: "rest of nigeria (delta)",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: " Hospitality & Leisure",
    itemValue: "hospitality",
    time: "18h",
    requirement: `An up scale Hotel is looking to employ an experience personnel for its operation
Accountant`,
  },
  {
    jobTitle: "Business development Manager",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    time: "19h",
    requirement: `The Company is a Multinational Branded Wear Importer having the exclusive & official License for several exclusive designer-wear Brands in Nigeria. We are looking for a qualified candidate with adequate years of experience to fill this position.`,
  },
  {
    jobTitle: "FREELANCE SALES REP",
    company: "Braykin Consulting Ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    time: "19h",
    requirement: `
Betacar.ng is the number 1 automotive e-commerce platform for Quality-certified cars in Nigeria. Providing online and offline sales channels for cars. We are currently hiring a results-driven freelance sales representative to join our Sales Team in Lagos. As a Beta car Freelance Sales Consultant; You get access to: Nigeria’s fastest-growing li ...
`,
  },
  {
    jobTitle: "MARKETING EXECUTIVE",
    company: "GEOMEL CONSULTS LIMITED",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    time: "19h",
    requirement: `We are looking for a suitable candidate to fill this position. Candidate must be within 23-35 years.
    `,
  },
  {
    jobTitle: "Field Sales Executive",
    company: "Anonymous Employer",
    location: "port Harcourt & Rivers State",
    jobType: "Full Time ",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    time: "20h",
    requirement: `A fast moving consumer goods company is in need of door-to-door sales executives to bring in new customers / retail shops in their neighborhood . Sales person only needs to have passion for sales and a win-win mentality.`,
  },
  {
    jobTitle: "Sales and Marketing Manager (Enugu)",
    company: "Anonymous Employer",
    location: "enugu",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    time: "20h",
    requirement: `The Sales and Marketing Manager is responsible for researching and developing marketing opportunities, also planning and implementing new sales plans. He/She will also manage both the marketing, sales staff and will perform managerial duties to meet the company's operations goals.
    `,
  },
  {
    jobTitle: "Nursery / Preschool Teacher",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    time: "20h",
    requirement: `A vibrant and experienced Nursery/ Preschool teacher. Candidate should have taught previously in the nursery or preschool class. The ideal candidate is expected to work with children aged 0-5 in classes between nursery, preschool and reception classes. His/her aim would be to motivate children; use resources to help them learn, whilst providing ...

`,
  },
  // {
  //   jobTitle: "",
  //   company: "",
  //   location: "",
  //   jobType: "",
  //   salary: "",
  //   jobModule: "",
  //   itemValue: "",
  //   time: "",
  //   requirement: ``,
  // },
];
