export const pageSix = [
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "",
    requirement: `
        `,
  },
];
