export const pageFour = [
  {
    jobTitle: "STORE KEEPER",
    company: "Robeck Locks Ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Supply Chain & Procurement",
    itemValue: "procurement",
    industry: "retail",
    time: "3d",
    requirement: `We are looking to hire Store keepers at our Warehouse.
        `,
  },
  {
    jobTitle: "Device Technician",
    company: "Moove Vehicle Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "travel",
    time: "3d",
    requirement: `The device technician will ensure that all devices and sensors in our vehicles are working from a hardware standpoint. 
        `,
  },
  {
    jobTitle: "Accountant",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "ngo",
    time: "3d",
    requirement: `You are expected to work with large amounts of numerical data, handle multiple tasks with deadlines, and provide transparent and complete reports to management. You should have a firm grasp of accounting and financial practices and regulations and possess strong computer and verbal and written communication skills.
        `,
  },
  {
    jobTitle: "Production Machine Operator",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Engineering & Technology",
    itemValue: "tech",
    industry: "manufacturing",
    time: "3d",
    requirement: `The role involves the operation and maintenance of semi-automatic encapsulation machines, labeling machine and other production and manufacturing machines. Previous experience with encapsulating is a plus but not mandatory.
        `,
  },
  {
    jobTitle: "Virtual Assistant/Remote HR personnel",
    company: "AFTJ Digital Marketing",
    location: "rest of nigeria(nationwide)",
    jobType: "Contract",
    salary: "Less than 75,000",
    jobModule: "Human Resources",
    itemValue: "hr",
    industry: "ngo",
    time: "3d",
    requirement: `AFTj Digital is a Digital Marketing and Software Solution company majorly made up of a remote workforce. We are currently in need of an agile virtual assistant to join our team.
        `,
  },
  {
    jobTitle: "DIRECT SALES EXECUTIVES",
    company: "ultraproco Investment Ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "adverts",
    time: "3d",
    requirement: `We are a Finance Company looking to hire for the position of Direct Sales Executives.
        `,
  },
  {
    jobTitle: "Finance Assistant",
    company: "VIP Express",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "ngo",
    time: "3d",
    requirement: `International Holiday Company seeks to fill this position with a suitable and qualified person
        `,
  },
  {
    jobTitle: "Direct Sales Agent",
    company: "Aposhashamura Finance Limited",
    location: "lagos",
    jobType: "Contract",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "3d",
    requirement: `We are seeking outgoing & customer service-oriented Direct Sales Agent (DSA) to join our organization. In this role, • The Employee’s Main Goal is to Generate Revenue for Aposhashamura. • The employee will market & sell one of Aposhashamura Investment Products, ‘Capify’ which is a Fixed Income Instrument & type: Debt Note (or Debt Financing)
        `,
  },
  {
    jobTitle: "Accountant",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "ngo",
    time: "3d",
    requirement: `This job is for an accountant with excellent knowledge of MsExcel and readiness to assist in administrative work.
        `,
  },
  {
    jobTitle: "Senior Lecturer",
    company: "UNIVERSITY",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Building & Architecture",
    itemValue: "building",
    industry: "education",
    time: "3d",
    requirement: `Nile University of Nigeria is a Private Institution located in Abuja, the Federal Capital Territory of Nigeria. The University was established in 2009 to provide high-quality tertiary education for the country’s ever-increasing number of secondary school leavers. In 2014, Nile University established its School of Postgraduate Studies. Today, ...
        `,
  },
  {
    jobTitle: "Customer Service Representative",
    company: "Justerotics",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "ngo",
    time: "3d",
    requirement: `We are looking to hire a Customer service representative in our Sex Toy Store.
        `,
  },
  {
    jobTitle: "Digital Skills Boot Camp Participants",
    company: "Modian Consulting Firm",
    location: "oyo",
    jobType: "Full Time",
    salary: "250,000 - 400,000 Negotiable",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "ngo",
    time: "3d",
    requirement: `If you have medium-to-advanced skills in any of the aforementioned digital skills and have some portfolios of previous works to demonstrate your existing skills, you are welcome to participate in our 3-month boot camp wherein you will be subjected to thorough training and drilled with many many real-life projects that meet international standar ...
        `,
  },
  {
    jobTitle: "Customer Care Officer",
    company: "Alex Reid West Africa",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "4d",
    requirement: `The company is looking to employ a cheerful, bright and hardworking young Customer Care Officer who will be able provide administrative , customer care duties in our Abuja Office. The successful candidate will also be smart, punctual and be responsible for carrying out administrative activities that facilitates the smooth running of the office.
        `,
  },
  {
    jobTitle: "MARKETING",
    company: "AVE MARIA MICROFINANCE INSTITUTION",
    location: "oyo",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "banking",
    time: "4d",
    requirement: `He/She will lead the design and implementation of all Marketing strategies to achieve the goals for all the microfinance banking products.
        `,
  },
  {
    jobTitle: "Account Manager",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    jobType: "Part Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "4d",
    requirement: `We are looking for an account manager that will be the face of our services and products. You will be the point of contact for our clients.
        `,
  },
  {
    jobTitle: "Nursery Teacher",
    company: "master'smark",
    location: "  lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "4d",
    requirement: `A passionate and enthusiastic educator with working knowledge of early childhood education and skillful childcare experience.
        `,
  },
  {
    jobTitle: "Admin Officer",
    company: "Deslog Training & Consulting Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "logistics",
    time: "4d",
    requirement: `In the quest for meeting up with the ever growing demands of our existing and prospective clients in Lagos, we are seeking to employ young, smart, innovative and highly experienced individuals who are goal oriented and dedicated to offering excellent service.
        `,
  },
  {
    jobTitle: "Office Assistant and Field Customer Service Staff",
    company: "Jekolo.com(Locomo Services Limited)",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Trades & Services",
    itemValue: "trades",
    industry: "ngo",
    time: "3d",
    requirement: `Jekolo is a leading online digital accessory store specializing in retail and wholesale supply of phone and accessories.
        `,
  },
  {
    jobTitle: "Graduate Trainee",
    company: "Talamus Nigeria",
    location: "lagos",
    jobType: "Contract ",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "4d",
    requirement: `An ideal candidate should be able to generate leads, recognize the needs of the clients and provide detailed information to the clients about the technical specifications of the software offered by Talamus.
        `,
  },
  {
    jobTitle: "Business Development Executive",
    company: "Anonymous Employer",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "logistics",
    time: "4d",
    requirement: `Branding, expansion in markets- online and physical, increase client base, and awareness. 
        `,
  },
];
