export const pageThree = [
  {
    jobTitle: "IT Support Support/Social Media Manager",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "1d",
    requirement: `IT Support Support/Social Media Manager needed for recruitment.

        `,
  },
  {
    jobTitle: "Sales Executive",
    company: "Snaphunt",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "1d",
    requirement: `The role is about New business generation by meeting potential clients to understand needs, provide relevant solutions and close new business opportunities. 
        `,
  },
  {
    jobTitle: "Project Supervisor",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Estate Agents & Property Management",
    itemValue: "estateManagement",
    industry: "realEstate",
    time: "1d",
    requirement: `We are looking to hire a young and highly cerebral Architect or Quantity Surveyor:
        `,
  },
  {
    jobTitle: "Purchasing Engineer",
    company: "Starzs Investments Company Limited",
    location: "rivers",
    jobType: "Full Time",
    salary: "150,000 - 250,000 Negotiable",
    jobModule: "Supply Chain & Procurement",
    itemValue: "procurement",
    industry: "logistics",
    time: "1d",
    requirement: `The Purchasing Engineer will handle buying an array of products/parts/consumables/spares linked to the overall engineering, mechanical, electrical chemical, and civil works of all Marine vessels in our fleet. He will act as a negotiator while sourcing items/materials at competitive prices.
        `,
  },
  {
    jobTitle: "Risk Internal Control and Audit Manager",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "1d",
    requirement: `The candidate will be responsible for assessing and identifying risks that could impede the reputation, safety, security, or financial success of the organization and auditing the company’s financial and information systems, assessing compliance with applicable standards and guidelines, and sufficiency of internal controls.
        `,
  },
  {
    jobTitle: "Digital Strategy Manager",
    company: "Etu Odi Communications",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "adverts",
    time: "1d",
    requirement: `The Digital Strategy Manager (DSM) is responsible for developing, managing, and implementing digital marketing strategies for the agency and our clients.
        `,
  },
  {
    jobTitle: "Student Counsellor (Study Abroad Assistant)",
    company: "TGM",
    location: "edo",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Consulting & Strategy",
    itemValue: "consulting",
    industry: "education",
    time: "1d",
    requirement: `Total support in organizing exhibitions and other educational fairs. Signing MOUs with potential partners. Attends training and seminars on behalf of TGM Education, a study abroad agency.
        `,
  },
  {
    jobTitle: "Quality Assurance Analyst",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Quality Control & Assurance",
    itemValue: "qualityControl",
    industry: "manufacturing",
    time: "1d",
    requirement: `We are looking for a Quality Assurance Analyst to join our growing team of engineers and contribute towards scaling the platform. The successful candidate will be responsible for ensuring application stability and quality assurance at all stages of software development and deployment. You will conduct automated and manual tests to ensure t ...
        `,
  },
  {
    jobTitle: "Contract and Procurement Officer",
    company:
      "Deutsche Gesellschaft fuer Internationale Zusammenarbeit (GIZ) GmbH",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Supply Chain & Procurement",
    itemValue: "procurement",
    industry: "logistics",
    time: "1d",
    requirement: `The contract and procurement officer will work with the ECOWAS Trade Facilitation West Africa (TFWA). The TFWA program is a multi-donor initiative supported by European Union, the Kingdom of the Netherlands, USAID, and Government of the Federal Republic of Germany, with GIZ and the World Bank Group as implementing partners. Overall, the program ...
        `,
  },
  {
    jobTitle: "Sales & Marketing Intern",
    company: "XAI Management Services Limited",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "adverts",
    time: "1d",
    requirement: `Do you have the ability to SELL and are interested in building your MARKETING skills? Here is a really exciting opportunity for you! Our client is a self-published author who creates and sells children's storybooks. The Sales & Marketing Intern will ensure that sales targets are met as agreed.
        `,
  },
  {
    jobTitle: "Further Mathematics teacher.",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "1d",
    requirement: `A further mathematics teacher is urgently needed in the school.
        `,
  },
  {
    jobTitle: "Janitor supervisor",
    company: "Total Facility management",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Estate Agents & Property Management",
    itemValue: "estateManagement",
    industry: "realEstate",
    time: "1d",
    requirement: `He/she will be in charge of the implementation of daily and weekly cleaning schedules at the facility.
        `,
  },
  {
    jobTitle: "Senior C# Developer",
    company: "Handfish",
    location: "rest of nigeria",
    jobType: "Contract",
    salary: "250,000 - 400,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "1d",
    requirement: `The main purpose of this role is to design IT solutions to satisfy new and changing business requirements. Interpret business requirements to design robust, efficient business systems aligned to the enterprise architecture strategy. We are looking for an innovative Polyglot Programmer experienced in a variety of different programming languages (C#
        `,
  },
  {
    jobTitle: "School Accountant - Female",
    company: "Midak Management Consults",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "education",
    time: "1d",
    requirement: `A private school in Ogudu, Lagos needs a female Accountant with a minimum work experience of 3 years.
        `,
  },
  {
    jobTitle: "Key Account Executive",
    company: "OGC Foods & Beverages Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "manufacturing",
    time: "1d",
    requirement: `Successful candidates will maintain relationships with existing clients and engage with prospective clients through the entire sales process.
        `,
  },
  {
    jobTitle: "Real Estate Consultant",
    company: "CRYSTGOLD CROWN LUXURY HOMES",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Estate Agents & Property Management",
    itemValue: "estateManagement",
    industry: "realEstate",
    time: "1d",
    requirement: `Our established real estate firm has more leads than we can reasonably manage, so we’re hoping to add two more experienced and licensed Real Estate Consultants to our team. The successful candidates will be responsible for overseeing a team of Sales Executive as well as brokering deals for the sale and business Investment. So if you have experience...
        `,
  },
  {
    jobTitle: "Treasury Officer",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "1d",
    requirement: `We are looking for a Treasury Officer to be our key liaison with the bankers, ensure payments are promptly made on approval, and be the final control check in the payable process. In this role, you will the eye of the owners of the business in ensuring that the day-to-day liquidity needs of the enterprise are met.
        `,
  },
  {
    jobTitle: "Front Desk Officer",
    company: "Abilat Concept Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "logistics",
    time: "1d",
    requirement: `Our company is looking for a professional Front Desk Clerk to oversee all receptionist and secretarial duties at our main entrance desk. You will perform a range of duties including answering phone calls, managing the switchboard, and maintaining the office budget.
        `,
  },
  {
    jobTitle: "Operations manager",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "logistics",
    time: "1d",
    requirement: `An Operations Manager is responsible for keeping track of the big picture and identifying potential areas of improvement. 
        `,
  },
];
