export const pageThree = [
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
  {
    jobTitle: "",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "",
    jobModule: "",
    itemValue: "",
    industry: "",
    time: "h",
    requirement: `
        `,
  },
];