export const pageFive = [
  {
    jobTitle: "General Manager",
    company: "KEMAPO NIGERIA LIMITED",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "logistics",
    time: "3d",
    requirement: `Provide leadership and direction to a team of people, Manage operations and finances of business, Recruit and train new hires on business practices, Drive development of employees, Ensure that quality of work or service is maintained, Plan and coordinate administrative procedures and system and devise ways to streamline processes etc.
        `,
  },
  {
    jobTitle: "MONTESSORI DIRECTRESS",
    company: "The Cedars World Nursery & Primary School",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "3d",
    requirement: `We are looking to hire a friendly and experienced Montessori personnel to provide guided learning, assist the children and meet their needs. 
        `,
  },
  {
    jobTitle: "Executive Assistant",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: " Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "3d",
    requirement: `We are looking for an Executive Assistant to the EXECUTIVE DIRECTOR (ED) to proactively provide timely, well-organized and professional administrative, logistic and secretarial support to the Office of the Executive Director. Candidate should reside within Victoria Island and its environs
        `,
  },
  {
    jobTitle: "Art Director",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "entertainment",
    time: "3d",
    requirement: `We are one of Nigeria’s leading Brand Communication firms working for some of Nigeria’s leading corporate entities and we’re looking for a candidate to fill the position of Art Director.
        `,
  },
  {
    jobTitle: "Office Assistant",
    company: "Prestigious Consulting Group",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "3d",
    requirement: `We are hiring for an Office Assistant to join our team
        `,
  },
  {
    jobTitle: "Product Owner (e-commerce)",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Product & Project Management",
    itemValue: "productManagement",
    industry: "retail",
    time: "3d",
    requirement: `We are a young start-up on the path to building a truly pan-African payments unicorn. We know we can do it – with a high-impact founding team and the backing from a multinational financial services company. You will have access to best-in-class engineering tools and resources to enable you to solve truly complex problems and develop game-changi ...
        `,
  },
  {
    jobTitle: "Mid-Wife",
    company: "Prestigious Consulting Group",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: " Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "3d",
    requirement: `We are hiring for an experienced Mid-wife to join our team
        `,
  },
  {
    jobTitle: "SOCIAL MEDIA MANAGER",
    company: "GEOMEL CONSULTS LIMITED",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "retail",
    time: "3d",
    requirement: `We are looking for a SOCIAL MEDIA MANAGER FOR A REAL ESTATE COMPANY.
        `,
  },
  {
    jobTitle: " Chief Technology Officer/Deputy Managing Director",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "3d",
    requirement: `We are looking to hire an expert in technological development to fill the position of Chief Technology Officer.
        `,
  },
  {
    jobTitle: "Pharmacy technician",
    company: "Prestigious Consulting Group",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "3d",
    requirement: `We are looking for an experience pharmacy technician to join our team, candidate should be ready to resume immediately.
        `,
  },
  {
    jobTitle: "Interior Architect/Interior Designer",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Building & Architecture",
    itemValue: "building",
    industry: "construction",
    time: "3d",
    requirement: `A reputable Interior Design company seeks to fill the above position with suitable and qualified persons. One with great attention to detail. Interpret design sketches on a design software
        `,
  },
  {
    jobTitle: "Social Media Administrator",
    company: "ICST Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "logistics",
    time: "3d",
    requirement: `We are looking for a suitable candidate to fill this position. Candidate must have adequate knowledge of social media tools.
        `,
  },
  {
    jobTitle: " Backend WEB Application Developer",
    company: "ICST Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "3d",
    requirement: `Candidate will work with a team in developing, implementing and supporting eLearning and eBusiness applications for web and mobile app (Android and IOS) platforms.
        `,
  },
  {
    jobTitle: "Frontend WEB Application Developer",
    company: "ICST Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    itemValue: "software",
    industry: "IT",
    time: "3d",
    requirement: `Will work with a team in developing, implementing and supporting eLearning and eBusiness applications for web and mobile app (Android and IOS) platforms.
        `,
  },
  {
    jobTitle: "Cashier",
    company: "E & P Hospitality",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "hotel",
    time: "3d",
    requirement: `We are looking to hire an experienced cashier to join our team to deliver outstanding customer service. The ideal candidate should possess excellent communication and interpersonal skills.
        `,
  },
  {
    jobTitle: " Operations/Location Manager (Hospitality)",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "hotel",
    time: "3d",
    requirement: `Our Company is looking to recruit an Operations Manager who will spearhead the 360 operations of the business. Responsibilities will include daily operations management, event management, and employee training. As our operations manager, you should be ready to mentor your team members, find ways to increase quality of customer service, and i ...
        `,
  },
  {
    jobTitle: "Office Assistant",
    company: "UCOM Technologies",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "IT",
    time: "3d",
    requirement: `A good office assistant, who is diligent and reliable
        `,
  },
  {
    jobTitle: " DIRECT SALES AGENT",
    company: "MetroHealth HMO Limited",
    location: "lagos",
    jobType: "Contract ",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "health",
    time: "3d",
    requirement: `MetroHealth HMO Limited is a Nationally accredited Health Management Organization with footprints in all the states of the federation. We are a technology driven organization within focus on seamless service to our members and hospitals on our network. Currently we are recruiting for the position of Direct Sales Agent.
        `,
  },
  {
    jobTitle: "ACCOUNTANT",
    company: "Robeck Locks Ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: " 75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "logistics",
    time: "3d",
    requirement: `We requirre an Accountant in our Hardoffice in Amwuo odofin
        `,
  },
  {
    jobTitle: "Accountant",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "ngo",
    time: "3d",
    requirement: `Our client, is a leader in agriculture, food processing, engineering production and argro allied industry and is seeking to recruit a young smart accountant providing financial control, compliance and system accounting management in a dynamic environment 
 `,
  },
];
