export const pageTen = [
  {
    jobTitle: "Store Manager",
    company: "Anonymous Employer",
    location: "abuja",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Food Services & Catering",
    itemValue: "foodServices",
    industry: "logistics",
    time: "8d",
    requirement: `The manager will oversee the high quality consumer experience, manage all aspects of the store and deliver on target to ensure the store's success,
        `,
  },
  {
    jobTitle: "Sales Engineer",
    company: "Telvida",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "IT",
    time: "8d",
    requirement: `We are looking for a seasoned, hardworking, smart and over achieving Sales Engineer with proven experience and a passion for selling technology solutions. You will be responsible for selling into new prospects as well as farming back into existing customers to ensure high renewal and customer satisfaction levels. 
        `,
  },
  {
    jobTitle: "Medical Officer",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "8d",
    requirement: `We are looking to hire a medical professional with extensive work experience to join other medical officers in a thriving Pediatric Hospital.
        `,
  },
  {
    jobTitle: "HEAD, TREASURY",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "600,000 - 900,000",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "ngo",
    time: "8d",
    requirement: `Responsible for executing the Bank's treasury function, efficiently measure & manage the treasury function and manage a team that performs a wide range of job duties and responsibilities.
        `,
  },
  {
    jobTitle: "Sales Executive",
    company: "Buy Plus Concept",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "8d",
    requirement: `We are currently recruiting for this position.
        `,
  },
  {
    jobTitle: "Business Development Expert",
    company: "Phlenu",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "logistics",
    time: "8d",
    requirement: `Phlenu is in search of a highly skilled Engagement Expert to join our team and help us continue our tradition of unparalleled [client/customer] satisfaction. We’re a company whose mission is to become Africa’s Global Marketplace. As an ideal candidate, you have a track record of outstanding sales/marketing experience.
        `,
  },
  {
    jobTitle: "Customer Service Engineer",
    company: "StreSERT Services Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Engineering & Technology",
    itemValue: "tech",
    industry: "logistics",
    time: "8d",
    requirement: `To oversee after-sales support to Clients, including the logistics and deployment of Technicians to provide installation, repairs and routine maintenance services
        `,
  },
  {
    jobTitle: "PROFESSIONAL CHEF",
    company: "Prestigious Consulting Group",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Food Services & Catering",
    itemValue: "foodServices",
    industry: "retail",
    time: "8d",
    requirement: `We are hiring for an experienced CHEF to join our team.
        `,
  },
  {
    jobTitle: "Marketing Executive",
    company: "Exodus petroleum ltd",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "energy",
    time: "8d",
    requirement: `Experience female marketing executive with minimum of two years marketing experience. She must be a goal getter and can work without supervision.
        `,
  },
  {
    jobTitle: "Sales Executive",
    company: "Kirby Nigeria",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "logistics",
    time: "8d",
    requirement: `We are looking for Sales Executive to act as the liaison between our clients and office. Your role will be to seek a new business opportunity by contacting and developing relationships with potential customers.To be successful in this Role, you will use your communication skills to cultivate strong relationships with customers.
        `,
  },
  {
    jobTitle: "FIELD ENGINEER – CIVIL ENGINEERING",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    exactLocation: "(edo)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Building & Architecture",
    itemValue: "building",
    industry: "ngo",
    time: "8d",
    requirement: `The company is an engineering company with expertise in design, engineering, procurement, construction as well as operation maintenance. The company primarily executes projects in the energy and infrastructure sectors for asset holding companies within the Group.
        `,
  },
  {
    jobTitle: " FIELD SURVEYOR",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    exactLocation: "(edo)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Building & Architecture",
    itemValue: "building",
    industry: "ngo",
    time: "8d",
    requirement: `The company is an engineering company with expertise in design, engineering, procurement, construction as well as operation maintenance. The company primarily executes projects in the energy and infrastructure sectors for asset holding companies within the Group.
        `,
  },
  {
    obTitle: "COMMERCIAL AND LEGAL ASSISTANT",
    company: "Anonymous Employer",
    location: "rest of nigeria",
    exactLocation: "(edo)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "8d",
    requirement: `The company is an engineering company with expertise in design, engineering, procurement, construction as well as operation maintenance. The company primarily executes projects in the energy and infrastructure sectors for asset holding companies within the Group.`,
  },

  {
    jobTitle: "Human Resource Analyst",
    company: "Aspire Power Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Human Resources",
    itemValue: "hr",
    industry: "energy",
    time: "8d",
    requirement: `The goal of the People Operations Analyst is to support in the selection, development and retention of the organization's employees in line with its values, mission, and vision.
        `,
  },
  {
    jobTitle: "Personal Trainer",
    company: "i-Fitness",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    industry: "logistics",
    time: "8d",
    requirement: `The candidate is a fitness enthusiast who helps clients keep fit and achieve their desired fitness goals.
        `,
  },
  {
    jobTitle: "Interior design",
    company: "Reflection interior design",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "realEstate",
    time: "8d",
    requirement: `To be able to manage clients and take orders online and ensure excellent delivery in service.
        `,
  },
  {
    jobTitle: "Office Assistant / Janitor",
    company: "ActivEdge Technologies Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "IT",
    time: "8d",
    requirement: `As an office assistant, you will provide support to front desk operations in the office. To ensure the office is clean and to maintain an effective environment both for employees and customers.
        `,
  },
  {
    jobTitle: "Security Officers/Guards at First Security Information Ltd",
    company: "First Security Information Ltd (FSI)",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Consulting & Strategy",
    itemValue: "consulting",
    industry: "security",
    time: "8d",
    requirement: `We are currently recruiting to fill this position
        `,
  },
  {
    jobTitle: "Office Manager Vacancy (Perfumery Superstore)",
    company: "StreSERT Services Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "logistics",
    time: "8d",
    requirement: `Our client is in the business of perfumery, representing various top fragrance brands in the world. As a result of expansion, the role of an Office Manager has become vacant and needs to be filled immediately. The Office Manager will essentially ensure the smooth running of the office on a day-to-day basis, and oversee administrative and opera ...
        `,
  },
  {
    jobTitle: "Sales and Marketing Executive",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "ngo",
    time: "8d",
    requirement: `We are looking to hire a young, super-intelligent University graduate to fill the position of Sales and Marketing Executive. You Should be able to sell ice to Eskimos. 
        `,
  },
];
