export const pageSeven = [
  {
    jobTitle: "HouseKeeper",
    company: "Aymie Staffing Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: " Trades & Services",
    itemValue: "trades",
    industry: "",
    time: "5d",
    requirement: `Urgently need of housekeepers to work with our clients and companies in lagos.
        `,
  },
  {
    jobTitle: "Laundry Man",
    company: "ELLIS SUITES LTD",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    industry: "hotel",
    time: "5d",
    requirement: `To oversee or operate dry-cleaning machines or washing machines for industrial or household items. These may include blankets, draperies, rugs, cloth garments, suede and fur. The workers may oversee other staff or work independently 
        `,
  },
  {
    jobTitle: "Bar man",
    company: "ELLIS SUITES LTD",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    industry: "hotel",
    time: "5d",
    requirement: `We are looking for a suitable candidate to fill this position.
        `,
  },
  {
    jobTitle: "Sales Associates",
    company: "FASTLANE EXPRESS INTERNATIONAL LIMITED",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "5d",
    requirement: `Customer focus and adaptability to different personality types. Ability to multi-task, set priorities and manage time effectively
        `,
  },
  {
    jobTitle: "Bar man",
    company: "Cr8 Careers Limited",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    industry: "hotel",
    time: "5d",
    requirement: `A 16-key Luxury Hotel & Lounge is looking to employ vibrant, experienced, and self-motivated hospitality personnel for its operations. You will Prepare alcohol or non-alcohol beverages for bar and restaurant patrons, Interact with customers, take orders and serve snacks and drinks, Assess customers’ needs and preferences, and make recommendations.
        `,
  },
  {
    jobTitle: "Customer Service Representative",
    company: "FASTLANE EXPRESS INTERNATIONAL LIMITED",
    location: "rest of nigeria",
    exactLocation: "(Akwa Ibom)",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "retail",
    time: "5d",
    requirement: `Customer focus and adaptability to different personality types. Ability to multi-task, set priorities and manage time effectively.
        `,
  },
  {
    jobTitle: "Investment Analyst/ Senior Analyst",
    company: "SahelCapital",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "5d",
    requirement: `To undertake financial research and report on prospective investment avenues, study how an investment is likely to perform and also participate in our sound portfolio-management strategy by providing the necessary data for our decision-making process.
        `,
  },
  {
    jobTitle: "EXECUTIVE WAITER/WAITRESS",
    company: "FarmCity Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Hospitality & Leisure",
    itemValue: "hospitality",
    industry: "hotel",
    time: "5d",
    requirement: `Communicate with customers about their orders Maintains excellent relationships with clients through superior customer service
        `,
  },
  {
    jobTitle: "Dispatch Rider",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "travel",
    time: "5d",
    requirement: `A top logistics company in Lagos is on the lookout for experienced dispatch rider who are ready to be recruited immediately
        `,
  },
  {
    jobTitle: "Facility Manager",
    company: "Obika Realtors Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Product & Project Management",
    itemValue: "projectManagement",
    industry: "realEstate",
    time: "5d",
    requirement: `We are looking for an experienced Manager for the post of a Facility Manager to lead our purpose driven team. Reporting to the company, who will provide guidance and support; you will draw upon your wide ranging experience to drive the successful management of the facility in keeping with the core values of our organisation.
        `,
  },
  {
    jobTitle: "WordPress Web Designer",
    company: "Hiltop Web Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "5d",
    requirement: `We currently seek to hire a talented, hardworking and result-oriented Web Designer who lives and breathes WordPress! Do you think this offer is yours? Are you creative enough to come up with design schemes; layout and colour chemistry in a way that knocks everyone off? Do you feel confident using new themes and plugins on live projects ...
        `,
  },
  {
    jobTitle: "SOCIAL MEDIA & DIGITAL MARKETING INTERN ",
    company: "AdwordsConsult",
    location: "lagos",
    jobType: "Internship & Graduate",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "adverts",
    time: "5d",
    requirement: `Paid Internship opportunity at our firm. We are looking for some energetic and dedicated fresh graduate for internship program. The candidate will be responsible for identifying the most effective ways of advertising or marketing company's products and services using various digital technologies. Good performers will be welcome to join the team.
        `,
  },
  {
    jobTitle: "dispatch rider",
    company: "sarabel logistics and security services limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "travel",
    time: "5d",
    requirement: `The dispatch rider will ensure timely movement and delivery of parcels, documents and go for other special deliveries.
        `,
  },
  {
    jobTitle: "Primary school Teacher",
    company: "Values Montessori School",
    location: "rest of nigeria",
    exactLocation: "(Osun)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "5d",
    requirement: `We are hiring for the role of Class Teacher in a Primary school.
        `,
  },
  {
    jobTitle: "Legal officer",
    company: "LEDAP",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Legal Services",
    itemValue: "legal",
    industry: "law",
    time: "5d",
    requirement: `LEDAP, an NGO of lawyers engaged in the promotion and protection of human rights, requires the services of an experience legal officer who would handle legal matters.
        `,
  },
  {
    jobTitle: "Secondary school Teacher (Mathematics)",
    company: "Values Montessori School",
    location: "rest of nigeria",
    exactLocation: "(Osun)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "5d",
    requirement: `We are hiring to fill the role of Mathematics Class Teacher.
        `,
  },
  {
    jobTitle: "Secondary school Teacher (English Language)",
    company: "Values Montessori School",
    location: "rest of nigeria",
    exactLocation: "(Osun)",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "5d",
    requirement: `We are looking to hire an experienced English language Secondary school teacher.
        `,
  },
  {
    jobTitle: "Assistant Sales",
    company: "i-Fitness",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "retail",
    time: "5d",
    requirement: `The candidate must be able to sale / engage with customers on the services & products of the company. The Candidate must live on the Mainland ( Surulere, Yaba & Ikeja)
        `,
  },
  {
    jobTitle: "Software Developer/Engineer",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "5d",
    requirement: `We are currently recruiting for a Software/Applications Developer. Experience in the Fintech or Banking industry is an added advantage. Kindly apply if you meet the requirements below: 
        `,
  },
];
