export const pageEight = [
  {
    jobTitle: "Corporate Driver",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "logistics",
    time: "6d",
    requirement: `We are looking for well-groomed driver who are ready to work in a corporate setting
        `,
  },
  {
    jobTitle: "Store Assistants",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "ngo",
    time: "6d",
    requirement: `To assist other senior store personnel in managing the company's stock 
        `,
  },
  {
    jobTitle: "IT/ SOFTWARE DEVELOPER",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "6d",
    requirement: `We are looking for a highly skilled software (Laravel) developer who is comfortable with both front and back end programming. You will be responsible for developing and designing front end web architecture, ensuring the responsiveness of applications, writing clean code and scalable algorithms. You will also be required to see out a project fro ...
        `,
  },
  {
    jobTitle: "Freight Forwarder,Secretary,Cleaning.",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Supply Chain & Procurement",
    itemValue: "procurement",
    industry: "retail",
    time: "6d",
    requirement: `The candidate will be responsible for ensuring the office space, receiving and forwarding calls to the right persons within the office, and other duties assigned from time to time.
        `,
  },
  {
    jobTitle: "Team Lead (Oyo and Saki branch)",
    company: "Anonymous Employer",
    location: "oyo",
    jobType: "Full Time",
    salary: "75,000 - 150,000 Negotiable",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "logistics",
    time: "6d",
    requirement: `Coordinate team members effort to achieve the organization goal
        `,
  },
  {
    jobTitle: "Credit officer",
    company: "Ave Maria Multipurpose Investment Limited",
    location: "oyo",
    jobType: "Full Time",
    salary: "Less than 75,000 Negotiable",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "retail",
    time: "6d",
    requirement: `Identify and give loan to credit worthy customer in our Oyo town or Saki branch
        `,
  },
  {
    jobTitle: "Design Manager",
    company: "MVUSA PROJEKTS",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Building & Architecture",
    itemValue: "building",
    industry: "construction",
    time: "6d",
    requirement: `The position will serve as a key member of the Design & Planning Team. The duties will include the architectural design of a variety of commercial buildings as well as master planning assignments. The individual should be well-organized, have good time management skills and be able to act with limited supervision.
        `,
  },
  {
    jobTitle: "Investment Analyst",
    company: "EjiCareers",
    location: "lagos",
    jobType: "Full Time",
    salary: "250,000 - 400,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "6d",
    requirement: `Nairametrics is a leading financial resource company based in Nigeria, with a special focus on financial literacy and investor advocacy. The Investment Analysts at Nairametrics candidate will be working with the editorial team to generate insightful articles on the investment landscape and report trends that are relevant to our target audience.
        `,
  },
  {
    jobTitle: "Business Development Executive(Male)",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "logistics",
    time: "6d",
    requirement: `We are looking for a suitable candidate with extensive knowledge and experience in this role to fill this position.
        `,
  },
  {
    jobTitle: "eCommerce Customer Success",
    company: "Hiltop Web Solutions",
    location: "rivers",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "IT",
    time: "6d",
    requirement: `Our eCommerce division seeks to hire highly motivated, experienced and hardworking customer support personnel to join our team.
        `,
  },
  {
    jobTitle: "WordPress Web Designer",
    company: "Hiltop Web Solutions",
    location: "rivers",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "6d",
    requirement: `We currently seek to hire a talented, hardworking and result-oriented Web Designer who lives and breathes WordPress! Do you think this offer is yours? Are you creative enough to come up with design schemes; layout and colour chemistry in a way that knocks everyone off? Do you feel confident using new themes and plugins on live projects ...
        `,
  },
  {
    jobTitle: "Application UX Designer",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "6d",
    requirement: `We are looking for a user-experience (UX) designer able to understand our business requirements and any technical limitations, as well as be responsible for conceiving and conducting user research, interviews and surveys, and translating them into sitemaps, user flows, customer journey maps, wireframes, mockups and prototypes.
        `,
  },
  {
    jobTitle: "Sales Accounts Manager - Security",
    company: "Polar Afpro Ltd",
    location: "lagos",
    jobType: "Contract",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "6d",
    requirement: `The candidate must have a minimum of 5 years verifiable working experience in corporate Sales Account Management; Must have experience in selling systems; Have a proven track record selling security solutions in Nigeria in both public and private sectors; Must have at least 3 years’ experience in selling Security solutions.
        `,
  },
  {
    jobTitle: "FINANCE EXECUTIVE",
    company: "MYD Telecoms Company Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "IT",
    time: "6d",
    requirement: `The Finance Manager is responsible for all areas relating to financial reporting, developing and maintaining accounting principles, practices, and procedures to ensure accurate and timely financial statements.
        `,
  },
  {
    jobTitle: "Dispatch Rider",
    company: "Aymie Staffing Solutions",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "logistics",
    time: "6d",
    requirement: `We are hiring urgently for the service of a Dispatch Rider
        `,
  },
  {
    jobTitle: "Business Intelligence & Analytics Expert",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "6d",
    requirement: `We are a leading Financial Institution currently hiring an experienced Business Intelligence Analyst to help us keep growing. Kindly apply if you fit this description.
        `,
  },
  {
    jobTitle: "Graphic Designer Intern",
    company: "Axon Analytics Ltd",
    location: "lagos",
    jobType: "Internship & Graduate",
    salary: "Less than 75,000",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "logistics",
    time: "6d",
    requirement: `Are you a fresh graduate interested in building real-world graphic design experience with an award-winning team? We’re a forward-thinking digital marketing agency looking for a talented and knowledgeable designer with fresh, creative ideas and an excellent eye for detail.
        `,
  },
  {
    jobTitle: "Sales Associate",
    company: "The Assembly Hub",
    location: "lagos",
    jobType: "Part Time",
    salary: "Less than 75,000",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "ngo",
    time: "6d",
    requirement: `The Brand is looking to hire a Sales Associate who will be in charge of sales facilitation. The perfect candidate should have a solid understanding of how their role fits into the grand scheme of its goals, as well as experience in a similar role.
        `,
  },
  {
    jobTitle: "Internal Control Officer",
    company: "Meridian Microfinance Bank Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "banking",
    time: "6d",
    requirement: `The Bank is in need of an experienced personnel in Auditing and Accounting with minimum of 3 years experience.
        `,
  },
  {
    jobTitle: "Facility Manager",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "logistics",
    time: "6d",
    requirement: `The Facility Manager's roles include but are not limited to Monitor, maintain and clean the office area, Perform work-related errands. Assist with planning and implementation of events. Create and update store inventory. Ensure that facilities meet government regulations and environmental, 
        `,
  },
];
