export const pageSix = [
  {
    jobTitle: "Finance Officer",
    company: "UNIVERSITY",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "education",
    time: "3d",
    requirement: `A competent Finance Officer with exceptional customer service, good problem-solving skills and that can engage and communicate with a variety of stakeholders. Nile University is seeking to engage highly competent and result-oriented individual with strong personal and professional integrity to join a dynamic team within the Finance Department.
        `,
  },
  {
    jobTitle: "Head/Principal (Nigerian or Expatriate)",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Research, Teaching & Training",
    itemValue: "teaching",
    industry: "education",
    time: "4d",
    requirement: `We are an Elementary School with state-of-the-art facilities and second to none, looking to hire a principal to meet the needs of students and staff members in order to ensure a conducive and productive learning environment.
        `,
  },
  {
    jobTitle: "SQL Server Database Administrator",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "4d",
    requirement: `We are currently recruiting for a Database Administrator with strong knowledge of indexes, index management, integrity checks, configuration and database patching. Kindly apply to this job if you meet the requirements above.
        `,
  },
  {
    jobTitle: "Client Service Executive",
    company: "Olunik Consulting Ltd",
    location: "ogun",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "logistics",
    time: "4d",
    requirement: `Our client, a Media Intelligence & Monitoring firm URGENTLY requires the service of a Client Service Executive.
        `,
  },
  {
    jobTitle: "Data Analyst",
    company: "Olunik Consulting Ltd",
    location: "ogun",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "4d",
    requirement: `Our client, a Media Intelligence & Monitoring firm URGENTLY requires the service of a Data Analyst
        `,
  },
  {
    jobTitle: "Front desk/Customer care officer (NYSC Corpers)",
    company: "OBN SPORTS BUSINESS WORLD LIMITED",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Customer Service & Support",
    itemValue: "customerService",
    industry: "entertainment",
    time: "4d",
    requirement: `We are looking to hire a young, smart corpers to fill the position of Front desk/ Customer care officer.
        `,
  },
  {
    jobTitle: "A CHARTERED ACCOUNTANT",
    company: "GEOMEL CONSULTS LIMITED",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "logistics",
    time: "4d",
    requirement: `We are looking for a suitable candidate with audit/tax experience to fill this position .
        `,
  },
  {
    jobTitle: "Bakery Manager",
    company: "betterloaf nig. ltd",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "retail",
    time: "4d",
    requirement: `We are looking to hire an experienced bakery manager to supervise our baking staff and manage all bakery operations.
        `,
  },
  {
    jobTitle: "Business Development Manager",
    company: "Nicole Sinclair",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "logistics",
    time: "4d",
    requirement: `Our Client is a brand Health and safety business, with offices within 5 countries in Africa, and opening up a branch in Nigeria.They are in need of a Business Development manager to focus on any of the following industries: Pharmaceutical , FMCG, Agro alied , Cosmetics and Animal Health and Vetenary Industries 
        `,
  },
  {
    jobTitle: "HEAD SALES/MARKETER",
    company: "",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "adverts",
    time: "4d",
    requirement: `We are looking for a suitable candidate to fill this position.
        `,
  },
  {
    jobTitle: "Marketing Executive",
    company: "Oxford Partners Zest Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "250,000 - 400,000",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "logistics",
    time: "4d",
    requirement: `If you live and breathe marketing, we need to talk. We’re looking for a flexible and versatile marketer who will be responsible for the growth of our inbound sales channels. To be successful in this role, you should have hands-on experience with web analytics tools and be able to turn creative ideas into effective advertising projects.
        `,
  },
  {
    jobTitle: "Accountant",
    company: "KEMAPO NIGERIA LIMITED",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Accounting, Auditing & Finance",
    itemValue: "accounting",
    industry: "ngo",
    time: "4d",
    requirement: `Minimum of Bachelor’s degree in Accountancy, Tax, and Finance • A professional accountancy qualification (ICAN, ANAN, ACA, ACCA, FCA) will be an added advantage • An MBA or other post-graduate professional qualification will be an added advantage • Minimum of 3 years significant commercial experience, preferably from FMCG, Banking sectors.
        `,
  },
  {
    jobTitle: "Human Resource Manager",
    company: "KEMAPO NIGERIA LIMITED",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Human Resources",
    itemValue: "hr",
    industry: "ngo",
    time: "4d",
    requirement: `Human resources (HR) officer is responsible for hiring, developing and looking after employees. This involves functions such as training and monitoring performance.

        `,
  },
  {
    jobTitle: "COO, Digital Agency",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Management & Business Development",
    itemValue: "busDev",
    industry: "logistics",
    time: "4d",
    requirement: `We are one of Nigeria’s leading Marketing Communications Business group working for some of Nigeria’s leading corporate entities and we’re looking for a candidate to fill the position of COO, Digital Agency Start-Up. This is a pioneering role within a marketing communications business group.
        `,
  },
  {
    jobTitle: "Technology Trainee",
    company: "Consulting Careers",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "4d",
    requirement: `Our client, a leading Multinational is currently recruiting for her Technology Graduate Trainee program. Kindly apply if you are skilled 
with builiding softwares and programming.
        `,
  },
  {
    jobTitle: "Fabric Cutter",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "logistics",
    time: "4d",
    requirement: `Cut Fabrics for coupling together
        `,
  },
  {
    jobTitle: "DRIVER",
    company: "The Cedars World Nursery & Primary School",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "education",
    time: "4d",
    requirement: `We are hiring for the position of the driver. `,
  },
  {
    jobTitle: "Sales personnel",
    company: "Neutratech Nigeria",
    location: "abuja",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "IT",
    time: "4d",
    requirement: `Are you an entrepreneur with a good attitude looking to expend your knowledge in the business world. If yes, you are who we are looking for, apply and join our team of excellent sales people.

        `,
  },
  {
    jobTitle: "Copywriter",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Creative & Design",
    itemValue: "creative",
    industry: "ngo",
    time: "4d",
    requirement: `We are one of Nigeria’s leading Brand Communication firms working for some of Nigeria’s leading corporate entities and we’re looking for a candidate to fill the position of Copywriter. 
        `,
  },
];
