export const pageNine = [
  {
    jobTitle: "Medical Doctor",
    company: "Healthrak",
    location: "lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "7d",
    requirement: `Medical doctor, also known as allopathic physician, take a biological approach to healing and are the most familiar type of doctor to people in this country. Most complete at least four years of undergraduate, followed by for years of medical school, and an additional residency program
        `,
  },
  {
    jobTitle: "DIGITAL MARKETER",
    company: "ROVEDANA LIMITED",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "logistics",
    time: "7d",
    requirement: `We are looking for a vast, efficient, and very proactive Digital Marketing Officer who can work with one of the leading property companies in Nigeria. 
        `,
  },
  {
    jobTitle: "Medical Doctor",
    company: "Healthrak",
    location: "oyo",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "7d",
    requirement: `Medical doctor, also known as allopathic physician, take a biological approach to healing and are the most familiar type of doctor to people in this country. Most complete at least four years of undergraduate, followed by for years of medical school, and an additional residency program
        `,
  },
  {
    jobTitle: "Senior Developer",
    company: "Desevens Digital",
    location: "abuja",
    jobType: "Full Time",
    salary: "250,000 - 400,000",
    jobModule: "Software & Data",
    itemValue: "software",
    industry: "IT",
    time: "7d",
    requirement: `We are looking for an experienced Senior Developer with extensive knowledge and experience in Craft CMS . He/she must be a self starter and will be responsible for overseeing projects and supporting various development duties.
        `,
  },
  {
    jobTitle: "Marketing Executive",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "ngo",
    time: "7d",
    requirement: `A reputable Radio Station in the English Format with its Head office in Lagos and branches in other state capitals requires a seasoned professional to fill the position of a Marketing Executive.
        `,
  },
  {
    jobTitle: "Sales Representative",
    company: "Recare LTD",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "7d",
    requirement: `Recare Limited, owners of Natures Gentle Touch, Non Stop & Hairsavvy, is a leader in the manufacturing and marketing of beauty and personal care products in Africa. With operations in Nigeria and South Africa, we provide key products and solutions to the beauty industry.
        `,
  },
  {
    jobTitle: "Field Sales Representative",
    company: "Moltizee International Services Limited",
    location: "oyo",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "7d",
    requirement: `Present, promote, and sell products to existing and prospective customers.
        `,
  },
  {
    jobTitle: "Head, Marketing",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Marketing & Communications",
    itemValue: "marketing",
    industry: "ngo",
    time: "7d",
    requirement: `A reputable Radio Station in the English Format with its Head office in Lagos and branches in other state capitals requires a seasoned professional to fill the under-listed position.
        `,
  },
  {
    jobTitle: "Junior Social Media Coordinator.",
    company: "Anonymous Employer",
    location: "abuja",
    jobType: "Full Time",
    salary: "Less than 75,000",
    jobModule: "Human Resources",
    itemValue: "hr",
    industry: "recruitment",
    time: "7d",
    requirement: `The appointee would be responsible for developing and executing a results-driven social media strategy, develop and create engaging content for social media across different platforms. Design, build and maintain a social media presence for the business, measure and report performance of all digital marketing campaigns.
        `,
  },
  {
    jobTitle: "Medical Doctor",
    company: "Healthrak",
    location: "rest of nigeria",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "7d",
    requirement: `Medical doctor, also known as allopathic physician, take a biological approach to healing and are the most familiar type of doctor to people in this country. Most complete at least four years of undergraduate, followed by for years of medical school, and an additional residency program.
        `,
  },
  {
    jobTitle: "Pharmacist",
    company: "Healthrak",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "7d",
    requirement: `We are recruiting to fill this position. The job opening is at Ikeja, Lagos
        `,
  },
  {
    jobTitle: "Personal Assistant",
    company: "Anonymous Employer",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "logistics",
    time: "7d",
    requirement: `Assist in the management and organization of employer's calendar by scheduling appointments, meetings, engagements, and daily activities, including running errands. Manage and coordinate travel for both business and personal arrangements. Spend time and become familiar with all aspects of business.
        `,
  },
  {
    jobTitle: "Radiographer",
    company: "Healthrak",
    location: "lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Medical & Pharmaceutical",
    itemValue: "medical",
    industry: "health",
    time: "7d",
    requirement: `Opening for a radiographer with adequate skills and knowledge.
        `,
  },
  {
    jobTitle: "Office Assistant / Janitor",
    company: "ActivEdge Technologies Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Admin & Office",
    itemValue: "admin",
    industry: "IT",
    time: "7d",
    requirement: `Provide support to front desk operations in the office. To ensure the office is clean and to maintain effective environment both for employees and customer.
        `,
  },
  {
    jobTitle: "Office Assistant / Janitor",
    company: "JUVANTE GROUP",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: " Admin & Office",
    itemValue: "admin",
    industry: "logistics",
    time: "7d",
    requirement: `Provide support to front desk operations in the office. To ensure the office is clean and to maintain effective environment both for employees and customer
        `,
  },
  {
    jobTitle: "Technical Sale Executive",
    company: "PC Recruit Nigeria",
    location: "lagos",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "7d",
    requirement: `Our Client requires an enthusiastic Technical sales professional in a predominantly office-based role, Providing high quality customer experience and reporting to the Head of Sales. This person will sell products to existing and potential customers, working as part of a team managing a geographic territory.
        `,
  },
  {
    jobTitle: "Retail Merchandising and Sales Officer (Fashion)",
    company: "360 Creative Innovation Hub",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "retail",
    time: "7d",
    requirement: `Idozi Collective is a premium retail brand of 360 Creative Hub Limited. Founded to connect African fashion products to the world, Idozi bridges the gap between African designers anddiscerning global markets who value technique and craftsmanship; the collective is curatedfor this specific taste via a multi-purpose retail channel. The Retail Me ...
        `,
  },
  {
    jobTitle: "Human Resources/Operation Officer",
    company: "360 Creative Innovation Hub",
    location: "lagos",
    jobType: "Full Time",
    salary: "Confidential",
    jobModule: "Human Resources",
    itemValue: "hr",
    industry: "IT",
    time: "7d",
    requirement: `The HR/Operations Officer will ensure the smooth running of all the administrative and operational aspects of 360 Creative Hub. Key areas of responsibility include HR, payroll management, and general administrative oversight.
        `,
  },
  {
    jobTitle: "LOGISTICS OFFICER",
    company: "Anonymous Employer",
    location: "rivers",
    jobType: "Full Time",
    salary: "75,000 - 150,000",
    jobModule: "Driver & Transport Services",
    itemValue: "transport",
    industry: "logistics",
    time: "7d",
    requirement: `we are looking for an experienced logistics officer who will ensure good relationship with transporters and representatives to ensure optimal vehicle deployment. He will effectively coordinate for deployment of internal resources – manpower, forklift, trailers to ensure seamless inbound and outbound operation.
        `,
  },
  {
    jobTitle: "Sales Executive",
    company: "Beta Analytics Limited",
    location: "lagos",
    jobType: "Full Time",
    salary: "150,000 - 250,000",
    jobModule: "Sales",
    itemValue: "sales",
    industry: "IT",
    time: "7d",
    requirement: `Responsible for scheduling appointment with prospects -Direct sales of the company's packages -One on one meeting and presentation of the company's offer to corporate bodies and high net worth individual 
        `,
  },
];
